# Generated by Django 5.2.1 on 2025-08-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='posts/')),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
